### ISSUE TITLE
Beta 1.1.0.112 Script Include VI error

### ISSUE THREAD

**Issue by srsmith99** [LabVIEW-DCAF/SharedMemoryModule#15] opened 2017-03-09 16:39 UTC
When attempting to execute the Script Include VI command in the configuration editor Tools tab, the algorithm fails and generates and Error 1498 at the Get LV Class Default Value By Name.vi. That vi is password protected. On my machine the Shared Memory runtime.lvclass is where I would expect (... LabVIEW 2016\vi.lib\NI\DCAF\Modules\Shared Memory\module\execution). 

The error 1498 data follows.

Possible reason(s):
LabVIEW:  Library has errors. Fix the errors before attempting this operation.

Complete call chain:
     Get LV Class Default Value By Name.vi
     class discovery singleton.lvlib:load class.vi
     class discovery singleton.lvlib:class discovery singleton.vi
     script includes VI.vi
     script includes loader.vi
     Standard Editor.lvlib:call include vi script.vi
     Standard Editor.lvlib:Configuration Utility.vi

LabVIEW attempted to find the class with this name:
Shared Memory runtime.lvclass

**Comment by leesecho** [comment] 2017-03-09 19:10
I have not been able to reproduce this issue with installation of the published DCAF Core package, plus the beta release packages. If you are able to pause work for ~15 minutes, I would recommend trying a mass compile (Tools >> Advanced >> Mass Compile...) of the DCAF directory (<LabVIEW>\vi.lib\NI\DCAF) on your development machine - If this does resolve your issue, we may be able to identify a package distribution issue.

**Comment by srsmith99** [comment] 2017-03-09 19:15
I will try that.

**Comment by srsmith99** [comment] 2017-03-09 20:45
Mass compile returned lots of errors so I reinstalled the vipc package. The Script Include VI is working now. Apparently the package did not install correctly the first time.

**Comment by leesecho** [comment] 2017-03-09 20:47
Ok, I will leave this issue open for now. Glad you have the function back.

**Comment by leesecho** [comment] 2017-03-23 17:56
@ryanpopo Is this related to the default value issue you resolved this week?

**Comment by ryanpoulos** [comment] 2017-03-23 18:02
@leesecho I don't think so. That was a CVT module issue that I discovered when migrating some of the CVT UI stuff over the Shared Memory module. I'm not sure the cause of this issue, but I suspect it might have been a one-off issue with a particular install since we have been using the Script Includes without a problem.

@srsmith99, have you encountered this issue at all with any of the beta packages since it was first reported?

**Comment by ryanpoulos** [comment] 2017-03-23 18:08
@srsmith99, never mind. I missed your previous comment that mentioned the issue being fixed with a package reinstall. This can probably be closed.

**Comment by leesecho** [comment] 2017-03-23 18:09
Thanks guys. Closing this issue.

**Closed as completed by leesecho** 2017-03-23 18:09 UTC

**Comment by srsmith99** [comment] 2017-03-23 18:16
Correct, no additional issues. No problem closing this one.
